//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.24 at 01:38:03 AM EDT 
//


package com.mitchell.examples.claim.mitchellclaimservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mitchell.examples.claim.mitchellclaimservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mitchell.examples.claim.mitchellclaimservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UpdateClaimRequest }
     * 
     */
    public UpdateClaimRequest createUpdateClaimRequest() {
        return new UpdateClaimRequest();
    }

    /**
     * Create an instance of {@link CreateClaimRequest }
     * 
     */
    public CreateClaimRequest createCreateClaimRequest() {
        return new CreateClaimRequest();
    }

    /**
     * Create an instance of {@link ReadClaimRequest }
     * 
     */
    public ReadClaimRequest createReadClaimRequest() {
        return new ReadClaimRequest();
    }

    /**
     * Create an instance of {@link ListOfClaims }
     * 
     */
    public ListOfClaims createListOfClaims() {
        return new ListOfClaims();
    }

    /**
     * Create an instance of {@link DateRangeRequest }
     * 
     */
    public DateRangeRequest createDateRangeRequest() {
        return new DateRangeRequest();
    }

    /**
     * Create an instance of {@link ClaimResponse }
     * 
     */
    public ClaimResponse createClaimResponse() {
        return new ClaimResponse();
    }

}
