//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.26 at 10:28:52 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/mitchell/examples/claim/mitchellclaimservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mitchell.examples.claim.mitchellclaimservice;
